== Goal _karaf:kar_

Except in unusual circumstances, use the <packaging>kar</packaging> to run this goal.

The _karaf:kar_ goal assembles a KAR archive from a features XML descriptor file, normally generated in the same project with the _karaf:features-generate-descriptor_ mojo.

== kar layout

There are two important directories in a kar:
repository/  contains a Maven structured repository of artifacts to be copied into the Karaf repository. The features descriptor and all the bundles mentioned in it are installed in this directory.
resources/ contains other resources to be copied over the Karaf installation.

Everything in target/classes is copied into the kar.  Therefore resources you want installed into Karaf need to be in e.g. src/main/resources/resources.  This choice is so other resources such as legal files from the maven-remote-resources-plugin can be included under META-INF in the kar, without getting installed into Karaf.

=== Example
[source,xml]
----
<project>
...
  <packaging>kar</packaging>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.karaf.tooling</groupId>
        <artifactId>karaf-maven-plugin</artifactId>
        <version>${project.version}</version>
        <extensions>true</extensions>
        <!-- There is no useful configuration for the kar mojo. The features-generate-descriptor mojo configuration may be useful -->
      </plugin>
    </plugins>
  </build>
</project>
----
