== Goal _karaf:features-add-to-repository_

Consider using the karaf-assembly packaging which makes it easy to assemble a custom distribution in one step instead of this individual goal.

The _karaf:features-add-to-repository_ goal adds all the required bundles for a given set of features into directory.  You can use this goal to create a _/system_ directory for building your own Karaf-based distribution.

By default, the Karaf core features descriptors (standard and enterprise) are automatically included in the descriptors set.

=== Example
The example below copies the bundles for the _spring_ and _war_ features defined in the Karaf features XML descriptor into the _target/features-repo_ directory.
[source,xml]
----
<project>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.karaf.tooling</groupId>
        <artifactId>karaf-maven-plugin</artifactId>
        <version>${project.version}</version>

        <executions>
          <execution>
            <id>features-add-to-repo</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>features-add-to-repository</goal>
            </goals>
            <configuration>
              <descriptors>
                <descriptor>mvn:org.apache.karaf.features/standard/3.0.0/xml/features</descriptor>
                <descriptor>mvn:my.groupid/my.artifactid/1.0.0/xml/features</descriptor>
              </descriptors>
              <features>
                <feature>spring</feature>
                <feature>war</feature>
                <feature>my</feature>
              </features>
              <repository>target/features-repo</repository>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
----

=== Parameters

[cols="1,1,5"]
|===
| Name | Type | Description
| _descriptors_ | _String[]_ | List of features XML descriptors where the features are defined 
| _features_ | _String[]_ | List of features that bundles should be copied to the repository directory
| _repository_ | _File_ | The directory where the bundles will be copied by the plugin goal 
|===
